### ISSUE TITLE
ActiveSupport::Logger.broadcast does not work for this plugin

### ISSUE THREAD

**Issue by hitochan777** [actindi/act-fluent-logger-rails#19]
When I follow the instruction of this repository's README, what happened is Rails no longer outputs to the default log which is created depending on the environments (e.g, log/development.log, config/production.log, etc) . Since I wanted Rails to output log to the default log file as well, I found [this page](http://railsware.com/blog/2014/08/07/rails-logging-into-several-backends/) and modified `config/environments/production.rb` as follows:

```uby
  # setting for logging
  config.log_level = :debug # there are six levels (debug info warn error fatal any). In debug mode the app logs everything.
  config.logger.extend ActiveSupport::Logger.broadcast(ActFluentLoggerRails::Logger.new(log_tags: {
      ip: :ip,
      ua: :user_agent,
      uid: ->(request) { request.session[:uid] }
  }))
  config.lograge.enabled = true
  config.lograge.formatter = Lograge::Formatters::Json.new
```

But unfortunately this doesn't work since `add` method of `FluentLogger` class does not post logs to fluentd, but `flush` method does, in my opinion. I am not so familiar with rails so maybe my guess is wrong. But can you propose any workaround for this problem?

**Comment by quek** [comment]
Rails outputs multiple times log per one request (FluentLogger#add is called multiple times in one request).
In order to want to output them together as one event of Fluentd,
FluentLogger#add dose not call Fluent::Logger::FluentLogger#post.
ActFluentLoggerRails::Logger#tagged calls Fluent::Logger::FluentLogger#post.

https://github.com/rails/rails/blob/master/railties/lib/rails/rack/logger.rb#L24
https://github.com/actindi/act-fluent-logger-rails/blob/master/lib/act-fluent-logger-rails/logger.rb#L49

**Comment by naiyt** [comment]
I've also run into this issue. @quek is there a workaround that you would recommend?

**Comment by naiyt** [comment]
We found a workaround by setting the `ActFluentLoggerRails::Logger` as the default logger, and *then* broadcasting the normal `ActiveSupport::TaggedLogging` logger. Something like this:

```ruby
tagged_file_logger = ::ActiveSupport::TaggedLogging.new(Logger.new(Rails.root.join("log", "#{Rails.env}.log")))

# Fluent logging
fluent_logger = ActFluentLoggerRails::Logger.new(log_tags: { uuid: :uuid })

# broadcast to file logger
fluent_logger.extend(ActiveSupport::Logger.broadcast(tagged_file_logger))

config.logger = fluent_logger
```

After doing that we get the logs both in the Rails log file and sent directly to fluent.

**Comment by hitochan777** [comment]
@naiyt Yes, I also ended up with this solution which seems to work fine but if you look carefully you will notice that tags are not output in `tagged_file_logger`. This is because `tagged` method is never called for the broadcasted loggers. That means only `add` for the subsequent loggers are called. Maybe we need to modify `broadcast` method?

**Comment by naiyt** [comment]
Good point @hitochan777...yeah, this is tricky. At this point I wonder  if it might be best to add a `broadcast` feature to `act-fluent-logger-rails` itself. I will give it a try and see what I can come up with.

**Comment by naiyt** [comment]
@hitochan777 here's what I've put together for now: https://github.com/mavenlink/act-fluent-logger-rails/commit/92e0437c9936dbbee783d2980dd979cfc6f8f474

Essentially I just added a `secondary_log` option to `ActFluentLoggerRails` to sort of handle its own `broadcast`. I was not having luck patching ActiveSupport's `broadcast`, so this seemed like an okay (if not great) compromise.

There are other subtle differences that will arise from this, I'm sure, so could use some testing before using in production...

**Comment by hitochan777** [comment]
@naiyt Thank you very much for your modification :+1:

**Comment by naiyt** [comment]
@hitochan777 @quek I've opened a PR here: https://github.com/actindi/act-fluent-logger-rails/pull/21

Open to a code review, or opinions on whether that is the right solution.

**Comment by danaronson** [comment]
anything going on with this.  I've run into this problem too.

**Comment by quek** [comment]
release 0.1.10
https://github.com/actindi/act-fluent-logger-rails/pull/27
