### ISSUE TITLE
Logging over http?

### ISSUE THREAD

**Issue by jrasanen** [actindi/act-fluent-logger-rails#34]
Is it possible to do log over http/https?

* http://docs.fluentd.org/articles/in_http
* http://docs.fluentd.org/articles/in_secure_forward

**Comment by quek** [comment]
I think it is not possible to do log over http/https.

act-fluent-logger-rails uses fluent/fluent-logger-ruby.
https://github.com/fluent/fluent-logger-ruby#fluent

I think fluent/fluent-logger-ruby is not support to log over http/https.

Thanks,
