### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by mattr** [actindi/act-fluent-logger-rails#71]
Rails 7 is out. Let's support it.

I've submitted a patch (PR: https://github.com/actindi/act-fluent-logger-rails/pull/70) to remove the upper bound on rails versions in the gemfile. (This could be set to `< 8.0`; however, unless or until the Rails team announce significant breaking changes, it may be better to leave it open-ended.)

Tested with Loki integration for a small app to confirm that it is working.

**Comment by s4na** [comment]
Thank you for PR.

https://github.com/actindi/act-fluent-logger-rails/pull/70
